name: Java CI with Maven and Docker in macOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    
    name: Build in macOS
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    
    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master
    
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    
    - name: Build with Maven
      run: mvn clean verify
      working-directory: agenda