name: Java CI with Maven and Docker on macOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    name: Build on macOS

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Colima and Docker CLI
        run: |
          brew install colima
          colima start --vm-type=qemu --cpu=2 --memory=2 --disk=10

      - name: Set up Docker environment
        run: |
          echo "DOCKER_HOST=unix://$HOME/.colima/default/docker.sock" >> $GITHUB_ENV
          echo "PATH=$HOME/.colima/bin:$PATH" >> $GITHUB_ENV

      - name: Check Docker
        run: docker version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Start MongoDB
        run: |
          docker run --name mongo -p 27017:27017 -d mongo:4.0.5
          sleep 10
          docker ps

      - name: Install XQuartz for headless testing
        run: brew install xquartz

      - name: Build and test with Maven
        run: |
          export DISPLAY=:99
          /opt/X11/bin/Xvfb :99 -screen 0 1024x768x16 &
          mvn clean verify
        working-directory: agenda

      - name: Stop MongoDB and Colima
        if: always()
        run: |
          docker stop mongo || true
          docker rm mongo || true
          colima stop