name: Java CI with Maven and Docker on macOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    name: Build on macOS

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Colima and Docker CLI
        run: |
          brew install colima docker
          colima start

      - name: Check Docker
        run: docker version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Start MongoDB
        run: |
          docker run --name mongo -p 27017:27017 -d mongo:4.0.5
          sleep 15
          docker ps

      - name: Install xvfb
        run: brew install XQuartz

      - name: Build and test with Maven
        run: xvfb-run mvn clean verify
        working-directory: agenda

      - name: Stop MongoDB
        if: always()
        run: |
          docker stop mongo || true
          docker rm mongo || true
          colima stop
